---
title: "Conceitos básicos de SQL"
description: |
  Significado de siglas e recomendações de leitura
author:
  - name: José de Jesus Filho
    url: https://rpg.consudata.com.br
date: 07-03-2021
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

 - SQL: Structured Query Language. Linguagem de acesso a bancos de dados. SQL é também usado para referir ao modelo de banco de dados baseado em schema: bases normalizadas e com restrições.
 
 - NoSQL: Not only SQL. Refere-se a uma veriedade de bancos de dados não baseados em schema. Sacrifica-se a segurança de um schema em favor de rapidez. Exemplos document stores, graph databases, key-value (json) etc.
 
 - Query: requisição enviada do cliente para o backend a fim de obter, inserir ou atualizar registros.
 
 - SGBD: sistema gerenciador de banco de dados, ex. PostgreSQL, MySQL, Oracle, MS SQL, SQLite...
 
 - Cluster: conjunto de banco de dados, usuários. Primeiro nível da hierarquia.
 
 - Banco de dados. Segundo nível da hierarquia. Consiste numa coleção de schemas.
 
 - Schema. Terceiro nível da hierarquia consiste num amespace para objetos SQL (tabelas, índices, sequências, triggers). Basicamente schema é uma coleção nomeada de objetos.
 
 -  Relações:
    -  Tabela
    -  Visão
    -  Sequências
    -  Índices
 
 - Heap
 - Toast: mecanismo pelo qual atributos muito grandes de uma linha são armazenados em outra tabela, chamada tabela TOAST (The Oversized-Attribute Storage Technique).
 
 - Atributos
 - Colunas
 -  Tuplas: linhas, registros
 -  Normalização
 -  Denormalização
 - Transação: begin  end (commit)
 -  Queries
 -  Subqueries
 -  CTEs
 - ACID: atomicidade, consistência, isolamento, durabilidade
 
A atomicidade garante que a transação se complete na base do tudo ou nada. Por exemplo, se dois usuários iniciam transações cujos resultados são incompatíveis, possivelmente ambas não serão completadas. 

Consistência assegura que uma alteração no banco deve ser válida e segue regras predefinidas.

Isolamento determina como uma transação é visível para outras transações.

Durabilidade assegura que transações completadas serão armazenadas permanentemente no banco de dados.

 - CRUD: Create, Read, Update, Delete
 - DDL: Data Defition Language
 - DML
 - Locks
 - Concorrência
 - MVCC
 - Bloats
 - Pivotagem
 - Window functions
 
 Siglas:
 
 DBA: Database administrator ou administrador do banco de dados
 DDL: Data Definition Language ou linguagem de definição de dados: CREATE, ALTER, DROP
 DML: Data Modification Language ou linguagem de modificação de dados: insert, update, delete
 DQL: linguagem de consulta de dados: select
 DTL: Linguagem de transação de dados: begin, dommit, rollback
 DCL: Linguagem de controle de dados: GRANT, REVOKE E DENY
 CRUD: CREATE, READ, UPDATE ou DELETE
 OLAP: Online Analytical Processing. Uso do banco como fonte para análise de dados e para dar seguimento do negócio. Basicamente é o uso do banco para compreender seu negócio.
 OLTP: Online Transaction Processing. 
 WAL: Write-Ahead-Log
 PAGE ou BLOCK  
 
## Recomendações de leitura

- [Documentação do PostgreSQL](https://www.postgresql.org/docs/)
- [Dicas de psql](https://psql-tips.org/psql_tips_all.html)
- [Dentro do PostgreSQL](https://www.interdb.jp/pg/)
- [Exercícios no PostgreSQL](https://pgexercises.com/)
- [Sintonizar (tunar) do postgresql.conf](https://pgtune.leopard.in.ua/)
- [Designing Data Intensive Applications](https://www.amazon.com.br/Designing-Data-Intensive-Applications-Martin-Kleppmann/dp/1449373321)
