library(distill)
create_post("Pivotagem com R e PostgreSQL")
create_post("Joins no R e no PostgreSQL")
create_post("TidyPG cheatsheet: Criando tabelas a partir de outras - parte 1")
create_post("Similaridades entre NA no R e NULL no PostgreSQL")
create_post("TidyPG cheatsheet: sumarizando tabelas com R e PostgreSQL")
create_post("Window functions no R e no PostgreSQL - Parte 1: aspectos estáticos")
create_post("Como subir múltiplos e grandes arquivos para o PostgreSQL com R")
create_post("R + PostgreSQL - distinct cheatsheet")
create_post("Busca textual com R, Shiny e PostgreSQL")
create_post("Chamando o R do PostgreSQL")
create_post("Trabalhando com mapas com R e PostgreSQL/PostGIS")
create_post("Colação no R e no PostgreSQL")
create_post("Papeis e usuários no PostgreSQL")
create_post("Componentes de memória do PostgreSQL")
create_post("Diagrama Entidade-Relacionamento com R e PostgreSQL")
create_post("Criando tabelas no PostgreSQL com e sem o R")
create_post("Tipos de dados no R e no PostgreSQL")
create_post("Backup com pg_dump no PostgreSQL")
create_post("Selecionar linhas aleatoriamente no PostgreSQL")
create_post("Dados categórios no R e no PostgreSQL")


